modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
modId="robotcontraption" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Robot Contraption" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
Add computer controlled contraption for Create mod.
'''

[[dependencies.robotcontraption]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.robotcontraption]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.robotcontraption]]
    modId="create"
    mandatory=true
    versionRange="[0.5a,0.6)"
    ordering="NONE"
    side="BOTH"

[[dependencies.robotcontraption]]
    modId="createaddition"
    mandatory=true
    versionRange="[1.18.2-20220712a,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.robotcontraption]]
    modId="computercraft"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.robotcontraption]]
    modId="flywheel"
    mandatory=true
    versionRange="[1.18-0.6.2,)"
    ordering="AFTER"
    side="CLIENT"
